//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAT.Gui.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAT.Gui.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Icon_YAT {
            get {
                object obj = ResourceManager.GetObject("Icon_YAT", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon_YAT_TerminalSettings {
            get {
                object obj = ResourceManager.GetObject("Icon_YAT_TerminalSettings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon_YAT_UserSettings {
            get {
                object obj = ResourceManager.GetObject("Icon_YAT_UserSettings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon_YAT_WorkspaceSettings {
            get {
                object obj = ResourceManager.GetObject("Icon_YAT_WorkspaceSettings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_ArrowRight_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_ArrowRight_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_ArrowRight_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_ArrowRight_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_CopyToClipboard_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_CopyToClipboard_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_CopyToClipboard_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_CopyToClipboard_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_CopyToFolder_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_CopyToFolder_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_CopyToFolder_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_CopyToFolder_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_Delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Delete_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_Delete_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_FolderClosed_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_FolderClosed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_FolderClosed_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_FolderClosed_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_FolderOpen_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_FolderOpen_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_FolderOpen_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_FolderOpen_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_FolderOptions_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_FolderOptions_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_FolderOptions_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_FolderOptions_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_LGPLv3_147x51 {
            get {
                object obj = ResourceManager.GetObject("Image_LGPLv3_147x51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_LGPLv3_88x31 {
            get {
                object obj = ResourceManager.GetObject("Image_LGPLv3_88x31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_NewDocument_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_NewDocument_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_NewDocument_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_NewDocument_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Off_12x12 {
            get {
                object obj = ResourceManager.GetObject("Image_Off_12x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_On_12x12 {
            get {
                object obj = ResourceManager.GetObject("Image_On_12x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_OpenDocument_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_OpenDocument_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_OpenDocument_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_OpenDocument_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Print_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_Print_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Print_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_Print_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Properties_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_Properties_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Properties_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_Properties_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_SaveDocument_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_SaveDocument_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_SaveDocument_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_SaveDocument_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Stop_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_Stop_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Stop_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_Stop_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Views_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_Views_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Views_24x24 {
            get {
                object obj = ResourceManager.GetObject("Image_Views_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_YAT_16x16 {
            get {
                object obj = ResourceManager.GetObject("Image_YAT_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_YAT_32x32 {
            get {
                object obj = ResourceManager.GetObject("Image_YAT_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_YAT_48x48 {
            get {
                object obj = ResourceManager.GetObject("Image_YAT_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_YAT_64x64 {
            get {
                object obj = ResourceManager.GetObject("Image_YAT_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
